#pragma once

enum XACT_WAVEBANK_GAMESOUNDS
{
    XACT_WAVEBANK_GAMESOUNDS_CHEERING = 0,
    XACT_WAVEBANK_GAMESOUNDS_JEE1 = 1,
    XACT_WAVEBANK_GAMESOUNDS_JEE2 = 2,
    XACT_WAVEBANK_GAMESOUNDS_JEE3 = 3,
    XACT_WAVEBANK_GAMESOUNDS_PEDALING = 4,
    XACT_WAVEBANK_GAMESOUNDS_ROLLING = 5,
    XACT_WAVEBANK_GAMESOUNDS_BIG_STONE = 6,
    XACT_WAVEBANK_GAMESOUNDS_MENU_CLICK = 7,
    XACT_WAVEBANK_GAMESOUNDS_AUTS1 = 8,
    XACT_WAVEBANK_GAMESOUNDS_AUTS2 = 9,
    XACT_WAVEBANK_GAMESOUNDS_AUTS3 = 10,
    XACT_WAVEBANK_GAMESOUNDS_BRAKE_SHORT = 11,
    XACT_WAVEBANK_GAMESOUNDS_BRAKE_LONG = 12,
    XACT_WAVEBANK_GAMESOUNDS_ROCK1 = 13,
    XACT_WAVEBANK_GAMESOUNDS_ROCK2 = 14,
    XACT_WAVEBANK_GAMESOUNDS_ROCK3 = 15,
    XACT_WAVEBANK_GAMESOUNDS_PEDAL1 = 16,
    XACT_WAVEBANK_GAMESOUNDS_PEDAL2 = 17,
    XACT_WAVEBANK_GAMESOUNDS_SPLASH = 18,
    XACT_WAVEBANK_GAMESOUNDS_THEME_HAPPY = 19,
    XACT_WAVEBANK_GAMESOUNDS_THEME_SAD = 20,
    XACT_WAVEBANK_GAMESOUNDS_THEME_START = 21,
    XACT_WAVEBANK_GAMESOUNDS_GRAVEL = 22,
};

#define XACT_WAVEBANK_GAMESOUNDS_ENTRY_COUNT 23
